version: '3'

services:
    db:
        image: 'postgres:12-alpine'
        container_name: 'postgres'
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - '54320:5432'
        volumes:
            - 'pgdata:/var/lib/postgresql/data'

    redis:
        container_name: 'redis'
        image: 'redis:6.0.1-alpine'
        ports:
            - '6379:6379'
        volumes:
            - 'redisdata:/data'

volumes:
    pgdata:
    redisdata:
