# Generated by Django 3.0.5 on 2020-05-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Title')),
                ('address', models.CharField(max_length=200, verbose_name='Listing Address')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('zipcode', models.CharField(max_length=20, verbose_name='State')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('bedrooms', models.PositiveIntegerField(default=1, verbose_name='BedRooms')),
                ('bathrooms', models.DecimalField(decimal_places=1, default=2, max_digits=2, verbose_name='BathRooms')),
                ('garage', models.PositiveIntegerField(default=0, verbose_name='Garage')),
                ('square_feet', models.IntegerField(blank=True, null=True, verbose_name='Square Feet')),
                ('lot_size', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Lot Size')),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Main Photo')),
                ('photo1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
            },
        ),
    ]
