# Generated by Django 3.0.5 on 2020-05-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='zipcode',
            field=models.CharField(max_length=20, verbose_name='ZipCode'),
        ),
    ]
