# Generated by Django 3.0.5 on 2020-05-06 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
        ('listings', '0002_auto_20200506_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='realtors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='listings', to='realtors.Realtor', verbose_name='Realtor'),
        ),
    ]
