# Generated by Django 3.0.5 on 2020-05-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_realtors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='realtors',
            new_name='realtor',
        ),
    ]
