# Generated by Django 3.0.5 on 2020-05-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('about', models.TextField(blank=True, verbose_name='About')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Photo')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Email')),
                ('is_mvp', models.NullBooleanField(verbose_name='Is MVP')),
                ('hired_at', models.DateField(auto_now_add=True, verbose_name='Hired At')),
            ],
            options={
                'verbose_name': 'Realtor',
                'verbose_name_plural': 'Realtors',
            },
        ),
    ]
