# Generated by Django 3.0.5 on 2020-05-06 14:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hired_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 6, 14, 36, 30, 674701, tzinfo=utc), verbose_name='Hired At'),
        ),
    ]
