# Generated by Django 3.0.5 on 2020-05-06 14:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_auto_20200506_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hired_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 6, 14, 48, 24, 119488, tzinfo=utc), verbose_name='Hired At'),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='is_mvp',
            field=models.BooleanField(default=False, verbose_name='Is MVP'),
        ),
    ]
