# Generated by Django 3.0.5 on 2020-05-07 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_auto_20200506_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hired_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Hired At'),
        ),
    ]
